### ISSUE TITLE
Typings removed

### ISSUE THREAD

**Issue by bryanjjohnson** [i18next/i18next-xhr-backend#239] opened 2016-09-20 21:08 UTC
I noticed you removed the typings in the last release. According to the commit, it was to make them available on DefinitelyTyped. They are currently not over there. Is there another option? (granted if you added it to the root level as index.d.ts, the typings would automagically be included with the project without further setup or downloads: http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html)

**Comment by jamuhl** [comment] 2016-09-21 05:21
the problem is i don't like to support typescript myself...nothing against people using it - having the files in the repo would mean i got to maintain that files.

on the other hand i see the growing demand (out of the angular2 world - why oh why?) plus the i18next API grown to a state of almost stable since moving to v2 - so there should be not to much work for keeping them uptodate once inside.

So i might be open to be added back - if added to all repos:
- https://github.com/i18next/i18next-xhr-backend
- https://github.com/i18next/i18next
- https://github.com/i18next/react-i18next
- https://github.com/i18next/i18next-intervalPlural-postProcessor
- https://github.com/i18next/i18next-browser-languageDetector
- https://github.com/i18next/i18next-localStorage-cache
- https://github.com/i18next/i18next-sprintf-postProcessor

does only makes sense if typescript is supported in all modules related to i18next not only in the xhr backend (thats the main reason i removed it).

You want to contribute that with PRs?

**Comment by bryanjjohnson** [comment] 2016-09-21 15:45
If you want to move it to DefinitleyTyped to match the other libraries in i18next, that's fine. The question I have is if you or someone else has attempted to move it over there yet?

**Comment by don-bluelinegrid** [comment] 2016-09-21 17:44
Why was this removed?
It broke a working project.

this should not have been completely eliminated, and if it is to be moved to DefinitelyTyped (which is less convenient for developers), then this would be a breaking change that needs clear documentation in the README.  The total removal is definitely a breaking change.

Don

**Comment by jamuhl** [comment] 2016-09-21 18:20
@bryanjjohnson no...no one moved it there

@don-bluelinegrid sorry for breaking your build, wasn't aware build chains depend on typescript (as i stated i don't use typescript - so nothing i'm an expert in not even a novice)

as said: if you want it to be more convenient...open PRs for stated repos

**Comment by bryanjjohnson** [comment] 2016-09-21 20:12
I'm trying to get it added to DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11384

**Comment by don-bluelinegrid** [comment] 2016-09-21 20:15
@bryanjjohnson 

So this means you will create, maintain, and provide the necessary TypeScript typings.  If you are doing that, why not deliver the typings with the module, rather than separating the typings.

DefintelyTyped exists primarily as a repository of typings files that have been created for modules that don't have typings, by people other than the author of the module.  Since you are the module creator and the module will have typings, it seems to make more sense to deliver the typings with the module, as a unified package.

Don

**Comment by bryanjjohnson** [comment] 2016-09-21 20:23
@don-bluelinegrid I'm not the module creator. I just was using the typings like you. And since it seems that the creator here doesn't want to maintain them anymore, I'm trying to move them to DT so that I can still use them (as well as people like you)

**Comment by don-bluelinegrid** [comment] 2016-09-21 20:30
@bryanjjohnson 
Sorry for the confusion.

My belief is that by moving the typings (and, an older version that may not match the current branch), this may have a negative consequence of not encouraging the module developer to maintain the typings.  If the typings from an older version (1.1.1, the last version with typings) are added to DefinitelyTyped, then who is going to continue to maintain those for version 1.2.0, 1.3.0, etc.?  And, bow do we know the 1.1.1 typings are correct for the current version, 1.1.2?

@jamuhl 
In order to use this xhr-backend module, we just need typings for this module.  We don't need typings for all of the other i18next modules.  It may be true (or not) that those other modules may not have proper typings, but this xhr module is used as a plugin or dependency in other projects, which don't require all of those other i18next modules.  So, I understand the thought about consistency, but that doesn't seem to be a compelling reason not to deliver the typings (which had already existed) with this xhr module.

Don

**Comment by jamuhl** [comment] 2016-09-21 21:35
@don-bluelinegrid i don't get it...you use the backend without i18next - or why you don't need the typings there? And even if so...why there should be typings in this repo (which is a plugin) and not in the main repo i18next or the other plugins? - i'm for all or nothing...:

a) We provide typings for all the i18next modules
b) We don't provide any at all and let consumers take care of it by trying to keep the files on DefinitelyTyped uptodate

Again. I use i18next a lot and in different projects  none of those uses typescript. No one will pay me the extra time i will need to support that. And believe it or not...maintaining this cost a lot of time - but i'm open to do so - just add uptodate versions for all repos mentioned and i will try my best to keep it in line with the codebase.

If you like to support the project have a look at http://locize.com our localization as a service offering - which will sponsor i18next in future.

**Comment by don-bluelinegrid** [comment] 2016-09-21 22:05
@jamuhl 

> i don't get it...you use the backend without i18next - or why you don't need the typings there?

Yes, I use the backend without i18next, from a consumer/dependency perspective.

I use the aurelia-i18n project.  aurelia-i18n is built on, and depends on, i18next.  However, I as a user of aurelia-i18n don't care about their dependency on i18next, and that is not visible to me.  They (the aurelia-i18n project) are the ones who may or may not need the typings for i18next.

I am only consuming i18next-xhr-backend, as a plugin for aurelia-i18n.  So, I only require the typings for the backend.

Again, I hear what you're saying about consistency, but the all or nothing approach may not be practical, from a delivery perspective.  This specific issue is logged only against the xhr-backend module, because there are people using that who have suffered from the change, which is breaking their projects.  They are not suffering because of any changes to the main i18next module.

So, it seems like a reasonable approach to put the typings back into the backend project, and then incrementally add them to the other i18next projects; assuming a decision is made to make these projects compatible with and support TypeScript.

Don

**Comment by jamuhl** [comment] 2016-09-22 07:16
@don-bluelinegrid look i made the decision caused by an issue about inconsistency having typescript files in this repo and for others just on DefinitelyTyped. So it was removed here. This decision might have been wrong out of your perspective as a user of aurelia - and yes if i had known this i would have made a breaking change - or not even done it.

Today...still not a fan of typescript i see the rising demand and offered you a solution - to maintain typescript definitions in future if added to all repos. Fair enough - isn't it?

**Comment by bryanjjohnson** [comment] 2016-09-22 15:04
@don-bluelinegrid My pull request has been approved. You can now download the typings with this: typings install --save --global dt~i18next-xhr-backend

**Comment by ErikSchierboom** [comment] 2016-10-20 11:43
@bryanjjohnson Thanks a lot, works perfectly!

**Comment by don-bluelinegrid** [comment] 2016-10-20 19:52
@bryanjjohnson 

Any idea why I am seeing this, in my webpack build, after installing the typings from DT?

```
ERROR in [default] /Users/donpeterkofsky/Documents/gc-2-dev/custom_typings/i18next-xhr-backend/index.d.ts:22:25 
Duplicate identifier 'Backend'.

ERROR in [default] /Users/donpeterkofsky/Documents/gc-2-dev/typings/globals/i18next-xhr-backend/index.d.ts:22:25 
Duplicate identifier 'Backend'.
```

I have this reference path in my own custom_typings directory:
```
/// <reference path="./i18next-xhr-backend/index.d.ts" />
```

I am using xhr-backend in conjunction with aurelia-i18n.

**Comment by ErikSchierboom** [comment] 2016-10-21 06:24
@don-bluelinegrid It looks like you haven't removed the old custom typings file in `/Users/donpeterkofsky/Documents/gc-2-dev/custom_typings/i18next-xhr-backend/index.d.ts`. Having installed the typings from DefinitelyTyped, you now have two equal typings files. Could you try removing `/Users/donpeterkofsky/Documents/gc-2-dev/custom_typings/i18next-xhr-backend/index.d.ts`? You shouldn't be needing that file anymore.

**Closed** 2016-11-07 12:22 UTC
